creation_rules:
  - path_regex: 'secrets/database/.*\.yaml$'
    age: 'age1yjn2ays8ttqx5x5620c7pkj9hsp9n9fhx62fghl0we9syhv5jyns86s6ja'
    
  - path_regex: 'k8s/secrets/.*\.yaml$'
    encrypted_regex: '^(data|stringData)$'
    age: 'age1yjn2ays8ttqx5x5620c7pkj9hsp9n9fhx62fghl0we9syhv5jyns86s6ja'

sops_version: 3.9.1
